import { MenuItem } from "@/types";

export const MENU_ITEMS: MenuItem[] = [
  // starter
  {
    id: "mm-001",
    name: "Mohinga",
    description: "The warm, aromatic fish broth is the ultimate comfort — like a gentle embrace for your tired soul.",
    cuisine: "Myanmar",
    course: "starter",
    price: 12,
    dietaryTags: [],
    moodTags: ["comforting", "nostalgic", "warming", "savory"],
    moodDescription: "The warm, aromatic fish broth is the ultimate comfort — like a gentle embrace for your tired soul.",
  },
  {
    id: "mm-002",
    name: "Tea Leaf Salad",
    description: "A crunchy, fermented tea leaf salad full of flavor and texture that acts as an adventurous wake-up call.",
    cuisine: "Myanmar",
    course: "starter",
    price: 10,
    dietaryTags: ["vegetarian"],
    moodTags: ["energizing", "refreshing", "adventurous", "spicy"],
    moodDescription: "A crunchy, fermented tea leaf salad full of flavor and texture that acts as an adventurous wake-up call.",
  },
  {
    id: "we-001",
    name: "Classic Caesar Salad",
    description: "Crisp romaine, creamy dressing, and garlic croutons. Simple, fresh, and highly reliable.",
    cuisine: "Western",
    course: "starter",
    price: 11,
    dietaryTags: [],
    moodTags: ["fresh", "light", "reliable", "classic"],
    moodDescription: "Crisp romaine, creamy dressing, and garlic croutons. Simple, fresh, and highly reliable.",
  },
  {
    id: "we-002",
    name: "Loaded Potato Soup",
    description: "Thick, creamy potato soup loaded with bacon, cheddar, and green onions. Cozy and indulgent.",
    cuisine: "Western",
    course: "starter",
    price: 10,
    dietaryTags: [],
    moodTags: ["cozy", "warming", "indulgent", "rich"],
    moodDescription: "Thick, creamy potato soup loaded with bacon, cheddar, and green onions. Cozy and indulgent.",
  },
  {
    id: "eu-001",
    name: "French Onion Soup",
    description: "Rich caramelized onion broth with a toasted bread slice topped with melted Gruyere cheese. Cozy and elegant.",
    cuisine: "European",
    course: "starter",
    price: 12,
    dietaryTags: [],
    moodTags: ["cozy", "warming", "elegant", "savory"],
    moodDescription: "Rich caramelized onion broth with a toasted bread slice topped with melted Gruyere cheese. Cozy and elegant.",
  },
  {
    id: "eu-002",
    name: "Smoked Salmon Tartare",
    description: "Delicate smoked salmon with capers, dill, and lemon. Refined, light, and romantic.",
    cuisine: "European",
    course: "starter",
    price: 14,
    dietaryTags: [],
    moodTags: ["refined", "light", "romantic", "fresh"],
    moodDescription: "Delicate smoked salmon with capers, dill, and lemon. Refined, light, and romantic.",
  },

  // main
  {
    id: "mm-003",
    name: "Shan Noodles",
    description: "Sticky rice noodles with savory chicken, crushed peanuts, and pickles. Cozy, gentle, and satisfying.",
    cuisine: "Myanmar",
    course: "main",
    price: 18,
    dietaryTags: [],
    moodTags: ["cozy", "gentle", "satisfying", "hearty"],
    moodDescription: "Sticky rice noodles with savory chicken, crushed peanuts, and pickles. Cozy, gentle, and satisfying.",
  },
  {
    id: "mm-004",
    name: "Slow-Cooked Pork Curry",
    description: "Tender, slow-braised pork belly in an aromatic ginger-garlic curry. Indulgent, hearty, and celebratory.",
    cuisine: "Myanmar",
    course: "main",
    price: 22,
    dietaryTags: [],
    moodTags: ["indulgent", "hearty", "celebratory", "spicy"],
    moodDescription: "Tender, slow-braised pork belly in an aromatic ginger-garlic curry. Indulgent, hearty, and celebratory.",
  },
  {
    id: "we-003",
    name: "Grilled Ribeye Steak",
    description: "Perfectly seared juicy ribeye with garlic butter and rosemary. Bold, rich, and highly celebratory.",
    cuisine: "Western",
    course: "main",
    price: 28,
    dietaryTags: [],
    moodTags: ["indulgent", "bold", "celebratory", "savory"],
    moodDescription: "Perfectly seared juicy ribeye with garlic butter and rosemary. Bold, rich, and highly celebratory.",
  },
  {
    id: "we-004",
    name: "Mushroom Risotto",
    description: "Creamy arborio rice with rich forest mushrooms and parmesan. Comforting, elegant, and calming.",
    cuisine: "Western",
    course: "main",
    price: 20,
    dietaryTags: ["vegetarian"],
    moodTags: ["comforting", "elegant", "calming", "creamy"],
    moodDescription: "Creamy arborio rice with rich forest mushrooms and parmesan. Comforting, elegant, and calming.",
  },
  {
    id: "eu-003",
    name: "Coq au Vin",
    description: "Classic French chicken braised in red wine, lardons, and mushrooms. Hearty, romantic, and sophisticated.",
    cuisine: "European",
    course: "main",
    price: 24,
    dietaryTags: [],
    moodTags: ["hearty", "romantic", "sophisticated", "rich"],
    moodDescription: "Classic French chicken braised in red wine, lardons, and mushrooms. Hearty, romantic, and sophisticated.",
  },
  {
    id: "eu-004",
    name: "Mediterranean Grilled Sea Bass",
    description: "Lightly grilled sea bass with olive oil, lemon, garlic, and fresh herbs. Refreshing, bright, and energizing.",
    cuisine: "European",
    course: "main",
    price: 26,
    dietaryTags: [],
    moodTags: ["refreshing", "bright", "energizing", "healthy"],
    moodDescription: "Lightly grilled sea bass with olive oil, lemon, garlic, and fresh herbs. Refreshing, bright, and energizing.",
  },

  // dessert
  {
    id: "mm-005",
    name: "Shwe Yin Aye",
    description: "Sweet coconut milk broth with agar jelly, sticky rice, and white bread. Refreshing, cooling, and playful.",
    cuisine: "Myanmar",
    course: "dessert",
    price: 8,
    dietaryTags: ["vegetarian"],
    moodTags: ["refreshing", "playful", "cooling", "sweet"],
    moodDescription: "Sweet coconut milk broth with agar jelly, sticky rice, and white bread. Refreshing, cooling, and playful.",
  },
  {
    id: "mm-006",
    name: "Mont Lone Yay Paw",
    description: "Traditional sticky rice balls stuffed with sweet palm jaggery, topped with grated coconut. Nostalgic and sweet.",
    cuisine: "Myanmar",
    course: "dessert",
    price: 8,
    dietaryTags: ["vegetarian"],
    moodTags: ["nostalgic", "sweet", "celebratory", "playful"],
    moodDescription: "Traditional sticky rice balls stuffed with sweet palm jaggery, topped with grated coconut. Nostalgic and sweet.",
  },
  {
    id: "we-005",
    name: "New York Cheesecake",
    description: "Classic dense, creamy cheesecake on a graham cracker crust. Rich, indulgent, and satisfying.",
    cuisine: "Western",
    course: "dessert",
    price: 10,
    dietaryTags: ["vegetarian"],
    moodTags: ["indulgent", "sweet", "satisfying", "rich"],
    moodDescription: "Classic dense, creamy cheesecake on a graham cracker crust. Rich, indulgent, and satisfying.",
  },
  {
    id: "we-006",
    name: "Apple Crumble",
    description: "Warm cinnamon apples baked under a golden oat crumble. Nostalgic, warm, and homey.",
    cuisine: "Western",
    course: "dessert",
    price: 9,
    dietaryTags: ["vegetarian"],
    moodTags: ["nostalgic", "warm", "homey", "sweet"],
    moodDescription: "Warm cinnamon apples baked under a golden oat crumble. Nostalgic, warm, and homey.",
  },
  {
    id: "eu-005",
    name: "Crème Brûlée",
    description: "Creamy vanilla custard base topped with a hard, contrastingly cool layer of caramelized sugar. Elegant and romantic.",
    cuisine: "European",
    course: "dessert",
    price: 11,
    dietaryTags: ["vegetarian"],
    moodTags: ["elegant", "romantic", "indulgent", "sweet"],
    moodDescription: "Creamy vanilla custard base topped with a hard, contrastingly cool layer of caramelized sugar. Elegant and romantic.",
  },
  {
    id: "eu-006",
    name: "Tiramisu",
    description: "Coffee-dipped ladyfingers layered with whipped mascarpone cream and cocoa powder. Romantic, bittersweet, and comforting.",
    cuisine: "European",
    course: "dessert",
    price: 11,
    dietaryTags: ["vegetarian"],
    moodTags: ["romantic", "bittersweet", "comforting", "rich"],
    moodDescription: "Coffee-dipped ladyfingers layered with whipped mascarpone cream and cocoa powder. Romantic, bittersweet, and comforting.",
  }
];
